name: Build Responder Windows Executable

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install Responder dependencies
          pip install netifaces twisted flask pycrypto pycryptodome pyopenssl ldapdomaindump
          # Additional networking libraries often used by Responder
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          # Create a simple entry point script that calls Responder's main function
          echo 'import sys; from Responder import main; sys.exit(main())' > responder_launcher.py
          # Use PyInstaller to create a standalone executable
          pyinstaller --onefile --name responder_windows_amd64.exe responder_launcher.py

      - name: Create zip file
        run: |
          Compress-Archive -Path .\dist\responder_windows_amd64.exe -DestinationPath responder_windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: responder-windows
          path: responder_windows.zip
